# Generated by Django 3.1.7 on 2021-03-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Foydalanuvchi ismi')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250, verbose_name="So'rov mavzusi")),
                ('message', models.TextField(verbose_name='Xabar')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="So'rov jonatilgan sana")),
                ('is_answered', models.BooleanField(default=False, verbose_name='Javob berildimi?')),
            ],
            options={
                'verbose_name': 'Zayavka',
                'verbose_name_plural': 'Zayavkalar',
                'ordering': ['-sent_at'],
            },
        ),
    ]
